// peoples-purse/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  constructor() { }

  userLoggedIn = sessionStorage.getItem('USER_ID') || sessionStorage.getItem('TEACHER_ID')

  ngOnInit(): void {
  }

}

<div class="footer">
    <div id="copyright">
        <p>People's Purse Copyright © 2021</p>
    </div>
    <h3 *ngIf="!userLoggedIn">
        <a class="button" routerLink="/educatorSignUp">
            Are you an educator?
        </a>
    </h3>
    <div id="voteLink">
        <a href="https://vote.gov/" target="_blank" rel="noopener noreferrer">
            <h3>Are you resgistered to vote?</h3>
        </a>
    </div>
</div>

// peoples-purse-next/components/footer.tsx
export default function Footer() {
    return (
        <div className="footer">
            <div id="copyright">
                <p>People's Purse Copyright © 2021</p>
            </div>
            <a href="https://vote.gov/" target="_blank" rel="noopener noreferrer">
                <h3>Are you resgistered to vote?</h3>
            </a>
        </div>
    )
}
