// peoples-purse/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  constructor() { }

  userLoggedIn = localStorage.getItem('USER_ID') || localStorage.getItem('TEACHER_ID')

  ngOnInit(): void {
  }

}

<div class="footer">
    <!-- copyright jazzmatazz -->
    <div id="copyright">
        <p>People's Purse Copyright © 2021</p>
    </div>
    <!-- educator link -->
    <h3>
        <a class="button" routerLink="/educatorSignUp">
            Are you an educator?
        </a>
    </h3>
    <!-- add in a link to voter registration link -->
    <div id="voteLink">
        <a href="https://vote.gov/" target="_blank" rel="noopener noreferrer">
            <h3>Are you resgistered to vote?</h3>
        </a>
    </div>
</div>

// components/footer.tsx
import Link from "next/link";

export default function Footer() {
    return (
        <footer className="page-footer" id='footer' style={{ padding: 20 }}>
            <div className="container" style={{ marginTop: 10, marginBottom: -10 }}>
                <div className="row">
                    <Link href='/about' passHref>
                        <div id='aboutLink' className="col s6" style={{ fontSize: 'large', marginLeft: -30, marginRight: 30 }}>
                            {"People's Purse Copyright © 2021"}
                        </div>
                    </Link>
                    <div className="col s6" style={{ textAlign: 'right', fontSize: 'large' }}>
                        <a id='voteLink' href="https://vote.gov/" target="_blank" rel="noopener noreferrer">
                            <i className="material-icons right">how_to_reg</i>
                            Are you registered to vote?
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    )
}
