// peoples-purse-next/pages/signUp.tsx
import {
    useMutation,
    gql
} from '@apollo/client';
import { useState } from 'react';

const SIGN_UP = gql`
mutation Mutation($input: UserSignUpInput!) {
    signUp(input: $input) {
      token
    }
  }
`

export default function SignUp() {
    const [signUp, { data, loading, error }] = useMutation(SIGN_UP);
    const [formState, setFormState] = useState({
        first_name: '',
        last_name: '',
        email: '',
        username: '',
        password: ''
    })

    const handleChange = (e: any) => {
        const { name, value } = e.target;
        setFormState({
            ...formState,
            [name]: value,
        });
    };

    if (loading) return 'Submitting...';
    if (error) return `Submission error! ${error.message}`;
    return (
        <>
            <form
                onSubmit={async (e: any) => {
                    e.preventDefault();
                    const signUpResponse = await signUp({
                        variables: {
                            input: {
                                first_name: formState.first_name,
                                last_name: formState.last_name,
                                email: formState.email,
                                username: formState.username,
                                password: formState.password
                            }
                        }
                    })
                    const token = signUpResponse.data.signUp.token
                    if(token){
                        localStorage.setItem('auth_token', token)
                        window.location.assign('/profile')
                    }
                }}
                className="signupForm"
            >
                <h3>Personal Information</h3>
                <label>First Name</label>
                <input
                    type='text'
                    name='first_name'
                    id='first_name'
                    onChange={handleChange}
                />
                <label>Last Name</label>
                <input
                    type='text'
                    name='last_name'
                    id='last_name'
                    onChange={handleChange}
                />
                <label>Username</label>
                <input
                    type='text'
                    name='username'
                    id='username'
                    onChange={handleChange}
                />
                <label>Email</label>
                <input
                    type='text'
                    name='email'
                    id='email'
                    onChange={handleChange}
                />
                <label>Password</label>
                <input
                    type='text'
                    name='password'
                    id='password'
                    onChange={handleChange}
                />
                <button
                    type='submit'
                >
                    Sign Up
                </button>
            </form>
        </>
    )
}

// peoples-purse/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { Apollo, gql } from 'apollo-angular';


const SIGN_UP = gql`
mutation Mutation($input: UserSignUpInput!) {
  signUp(input: $input){
    token
    user {
      id
    }
  }
}
`;

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})

export class SignupComponent implements OnInit {

  constructor(private apollo: Apollo) { }

  ngOnInit(): void {
  }

  showClassInput() {
    let classCodeDiv = document.getElementById('ClassCodeInput');
    classCodeDiv?.style.display != 'none' ? classCodeDiv?.setAttribute('style', 'display: none') : classCodeDiv.setAttribute('style', 'display: block')
  }

  username = '';
  email = '';
  password = '';
  classCode = '';

  setUsername(event: Event) {
    this.username = (event.target as HTMLInputElement).value;
  }

  setEmail(event: Event) {
    this.email = (event.target as HTMLInputElement).value;
  }

  setPassword(event: Event) {
    this.password = (event.target as HTMLInputElement).value;
  }

  setClassCode(event: Event) {
    this.classCode = (event.target as HTMLInputElement).value;
  }

  signUp(event: Event) {
    // comment out
    event.preventDefault()

    this.apollo.mutate({
      mutation: SIGN_UP,
      variables: {
        input: {
          email: this.email,
          username: this.username,
          password: this.password,
          classCode: this.classCode
        }
      }
    }).subscribe(({ data }: any) => {
      console.log('got data', data);
      const token = data.signUp.token;
      const userId = data.signUp.user.id;
      localStorage.setItem('USER', this.username)
      localStorage.setItem('USER_ID', userId)
      localStorage.setItem('AUTH_TOKEN', token)
      // load to profile page
      window.location.replace('/profile')
    }, (error) => {
      console.log('there was an error sending the query', error);
    });
  }

}

<h1>Sign Up</h1>
<form>
    <div class="row">
        <label>Username</label>
        <input type="text" placeholder="Username" (change)="setUsername($event)" />
    </div>
    <div class="row">
        <label>Email</label>
        <input type="text" placeholder="Email" (change)="setEmail($event)" />
    </div>
    <label>Password</label>
    <input type="text" placeholder="Password" (change)="setPassword($event)" />
    <div class="row">
        <label>Have a class code?</label>
        <input type="checkbox" (click)="showClassInput()" />
    </div>
    <div class="row" id="ClassCodeInput" style="display: none">
        <label>Enter it here</label>
        <input type="string" (change)="setClassCode($event)" />
    </div>
    <button (click)="signUp($event)">
        Sign Up
    </button>
</form>
<h3>
    <a class="button" routerLink="/login">Returning User?
        <br />
        Login Here</a>
</h3>
<br />
<p>
    <a class="button" routerLink="/educatorSignUp">
        Are you an educator?
    </a>
</p>
